stages:
- build
- test
- e2e
- build_images

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

.build:
  image: node:21
  only:
  - main
  stage: build
  script:
  - echo "Build job started..."
  - npm install -g @nestjs/cli
  # Problem microservice
  - cd problem-microservice
  - npm install
  - npm run build
  # Runner microservice
  - cd ../runner-microservice
  - npm install
  - npm run build
  # User microservice
  - cd ../user-microservice
  - npm install
  - npm run build
  # Frontend
  - cd ../frontend
  - npm install
  - npm run build

.test:
  image: node:21
  only:
  - main
  stage: test
  script:
  - echo "Test job started..."
  - npm install -g @nestjs/cli
  # Problem microservice
  - cd problem-microservice
  - npm install
  - npm run test
  - npm run test:cov
  # Runner microservice
  - cd ../runner-microservice
  - npm install
  - npm run test
  - npm run test:cov
  # User microservice
  - cd ../user-microservice
  - npm install
  - npm run test
  - npm run test:cov


.e2e:
  only:
  - main
  stage: e2e
  image: docker
  services:
    - docker:dind
  script:
  - echo "E2E job started..."
  - cp .env.compose.example .env.compose
  - docker compose down -v # clear any cached volumes
  - docker compose up -d
  - docker exec playwright sh -c "pwd" # Verify that the playwright container
  - docker exec playwright sh -c "ls"  # properly mounted the frontend directory
  - docker exec playwright sh -c "npm install"
  - docker exec playwright sh -c "npx playwright test"

build_images:
  only:
  - main
  stage: build_images
  image: docker
  services:
    - docker:dind
  script:
  - echo "Build docker images job started..."
  - cd frontend
  - docker build -t $DOCKER_USER/frontend --build-arg PORT=3333 --build-arg GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID --build-arg GATEWAY_URL=http://localhost:8000 .
  - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
  - docker push $DOCKER_USER/frontend
  # - docker build -t problem-ms ./problem-microservice
  # - docker build -t runner-ms ./runner-microservice
  # - docker build -t user-ms ./user-microservice

  