stages:
- build
- test
- e2e

build:
  only:
  - main
  stage: build
  script:
  - echo "Build job started..."
  - npm install -g @nestjs/cli
  # Problem microservice
  - cd problem-microservice
  - npm install
  - npm run build
  # Runner microservice
  - cd ../runner-microservice
  - npm install
  - npm run build
  # User microservice
  - cd ../user-microservice
  - npm install
  - npm run build
  # Frontend
  - cd ../frontend
  - npm install
  - npm run build

test:
  only:
  - main
  stage: test
  script:
  - echo "Test job started..."
  - npm install -g @nestjs/cli
  - cd problem-microservice
  - npm install
  - npm run test
  - cd ../runner-microservice
  - npm install
  - npm run test
  - cd ../user-microservice
  - npm install
  - npm run test

e2e:
  only:
  - main
  stage: e2e
  image: "mcr.microsoft.com/playwright:v1.40.0-jammy"
  script:
  - echo "E2E job started..."
  - cd frontend
  - npm install
  - npx playwright install --with-deps
  - npx playwright test


  