stages:
- build
- test
- e2e

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  image: node:21
  only:
  - main
  stage: build
  script:
  - echo "Build job started..."
  - npm install -g @nestjs/cli
  # Problem microservice
  - cd problem-microservice
  - npm install
  - npm run build
  # Runner microservice
  - cd ../runner-microservice
  - npm install
  - npm run build
  # User microservice
  - cd ../user-microservice
  - npm install
  - npm run build
  # Frontend
  - cd ../frontend
  - npm install
  - npm run build

test:
  image: node:21
  only:
  - main
  stage: test
  script:
  - echo "Test job started..."
  - npm install -g @nestjs/cli
  - cd problem-microservice
  - npm install
  - npm run test
  - cd ../runner-microservice
  - npm install
  - npm run test
  - cd ../user-microservice
  - npm install
  - npm run test

e2e:
  only:
  - main
  stage: e2e
  image: docker
  services:
    - docker:dind
  script:
  - echo "E2E job started..."
  - cp .env.compose.example .env.compose
  - docker compose down -v # clear any cached volumes
  - docker compose up -d
  - docker exec playwright sh -c "pwd" # Verify that the playwright container
  - docker exec playwright sh -c "ls"  # properly mounted the frontend directory
  - docker exec playwright sh -c "npm install"
  - docker exec playwright sh -c "npx playwright test"

  