version: '3.8'
services:
  problem-ms:
    container_name: problem-ms
    build: ./problem-microservice
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_NAME=problem-ms
      - RABBITMQ_HOST=rabbitmq-e2e
    env_file:
      - .env.compose
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  user-ms:
    container_name: user-ms
    build: ./user-microservice
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_NAME=user-ms
      - RABBITMQ_HOST=rabbitmq-e2e
      - GITHUB_CLIENT_ID=ffeb9e270b563c7ba883
    env_file:
      - .env.compose
    depends_on:
      rabbitmq:
        condition: service_healthy

  runner-ms:
    container_name: runner-ms
    build: ./runner-microservice
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - RABBITMQ_HOST=rabbitmq-e2e
    env_file:
      - .env.compose
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  db:
    container_name: db
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 10s
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    container_name: rabbitmq-e2e
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 20s
      retries: 10
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      db:
        condition: service_healthy

  gateway:
    container_name: gateway
    build: ./gateway
    environment:
      - USER_MS=user-ms:3001
      - PROBLEM_MS=problem-ms:3000
      - RUNNER_MS=runner-ms:3002
    depends_on:
      - problem-ms
      - user-ms
      - runner-ms
    ports:
      - 8000:8000
  
  frontend:
    container_name: cc-frontend
    build:
      context: ./frontend
      args:
        PORT: 3333
        GATEWAY_URL: http://localhost:8000
        GITHUB_CLIENT_ID: ffeb9e270b563c7ba883
    depends_on:
      - gateway
      - problem-ms
      - user-ms
      - runner-ms
    ports:
      - 3333:3333

  playwright:
    container_name: playwright
    image: "mcr.microsoft.com/playwright:v1.43.0-jammy"
    volumes:
      - ./frontend:/usr/src/app
    entrypoint: /bin/bash
    working_dir: /usr/src/app
    network_mode: "host"
    ipc: host
    tty: true
    stdin_open: true
    depends_on:
      - frontend
      - problem-ms
      - user-ms
      - runner-ms
volumes:
  db_data: